import type { Metadata } from "next";
import { Martel, Open_Sans, Poppins } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({});
const martel = Martel({ weight: "700", variable: "--font-martel" });
const poppins = Poppins({ weight: "400", variable: "--font-poppins" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className="scrollbar scrollbar-track-transparent scrollbar-thumb-brand-400 scrollbar-thumb-rounded-full scroll-smooth"
    >
      <body
        className={`${openSans.className} ${martel.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
