import type { Metadata } from "next";
import { Martel, Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({});
const martel = Martel({ weight: "700", variable: "--font-martel" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${openSans.className} ${martel.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
